# referencing https://abronan.com/building-a-rust-project-on-circleci/
version: 2
jobs:
    coverage: 
        machine: true
        steps:
            - checkout
            - run:
                name: Docker coverage
                command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin
    test:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - restore-cache:
                key: project-cache
            - run:
                name: Lint
                command: |
                    rustfmt --version
                    cargo fmt -- --check
            - run: 
                name: Test
                command: cargo test
            - save-cache: 
                key: project-cache
                paths:
                    - ~/.cargo
                    - ./target
workflows:
    version: 2
    test_and_coverage:
        jobs:
            - test
            - coverage